### ISSUE TITLE
Integration Test for Google Cloud Platform Deployment

### ISSUE THREAD

**Issue by gmcfall** [konigio/konig#594]
The Konig Toolkit builds a deployment script for Google Cloud Platform resources (BigQuery dataset, BigQuery tables, PubSub topics)

We need an automated integration test which verifies that the generated script works as expected.

### Acceptance Criteria

* There exists a spreadsheet that contains the semantic model that will be used in the integration test
* There exists a maven project that parses the spreadsheet and builds a corresponding GCP project including the deployment script.
* There exists an integration test that executes the deployment script and confirms that it produces the correct resources in GCP.
* The groovy deployment script must throw a RuntimeException if an error occurs during the deployment.
* If a RuntimException is thrown, the integration test must catch it and report the error. 
* Before executing the deployment script, the integration test must run a tear-down script to ensure that none of the resources currently exist within the project (see Issue #601).
* After executing the deployment script , the integration test must make its own calls to the Google Cloud Platform and independently verify that the resources were deployed successfully.  It is not sufficient to assume that the script worked properly just because it exited without throwing an exception.
* After executing the deployment script, the integration test must run the tear-down script again.
* After running the tear-down script, the integration test must make its own calls to the Google Cloud Platform and independently verify that the resources were successfully removed.

### Implementation Notes
See [Integration Testing With Maven](https://www.petrikainulainen.net/programming/maven/integration-testing-with-maven/) for information about setting up and running integration tests.

Here's a rough sketch of a possible solution:

1.  Create a new maven project named `gcp-integration-test` within the [konig](https://github.com/konigio/konig) GitHub repository.  This project will house the integration test.
2.  Copy the contents of [gcp-multi-project](https://github.com/konigio/konig-examples/tree/master/gcp/gcp-multi-project) to `gcp-deploy-test/src/test/resources/gcp-multi-project`
3. Modify the configuration of the multi-project so that it will only build the RDF model and the GCP model.  For the purposes of this integration test, we don't need to build the data catalog or data services.
4. Write a JUnit test method that builds the gcp-multi-project from the location in Step 2.  Ideally, this method should rely in the `autoBuild=true` configuration setting from Issue #599.  This means that a single invocation of the master project will generate the suite of child projects and then build them; you won't need to explicitly build the child projects.  Until #599 is completed, however, the integration test will have to generate the maven projects and then separately run `mvn install` on the generated parent project.

**Comment by gmcfall** [comment]
This issue was closed accidentally.

**Comment by gmcfall** [comment]
When I run the integration test, I get the following error...

```
java.lang.IllegalStateException: Maven application directory was not specified, and ${maven.home} is not provided in the system properties. Please specify at least on of these.
	at org.apache.maven.shared.invoker.MavenCommandLineBuilder.checkRequiredState(MavenCommandLineBuilder.java:124)
	at org.apache.maven.shared.invoker.MavenCommandLineBuilder.build(MavenCommandLineBuilder.java:59)
	at org.apache.maven.shared.invoker.DefaultInvoker.execute(DefaultInvoker.java:101)
	at io.konig.test.GcpDeploymentTest.test1GcpMultiProject(GcpDeploymentTest.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```
